### ISSUE TITLE
Fix favoriting and unfavoriting a player

### ISSUE THREAD

**Issue by andreiboyanov** [andreiboyanov/soumarin#1]
An exception is thrown if one tries to tap in the heart icon in the players list

**Comment by andreiboyanov** [comment]
The following exception occurs:

E/flutter (22209): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (22209): type 'Future<dynamic>' is not a subtype of type 'Future<Record>' in type cast where
E/flutter (22209):   Future is from dart:async
E/flutter (22209):   Future is from dart:async
E/flutter (22209):   Record is from package:sembast/sembast.dart
E/flutter (22209): 
E/flutter (22209): #0      Object._as (dart:core/runtime/libobject_patch.dart:67:25)
E/flutter (22209): #1      Database.putRecord (file:///home/andrei/.pub-cache/hosted/pub.dartlang.org/sembast-1.6.1/lib/src/sembast_database.dart:247:8)
E/flutter (22209): #2      SousMarinDb.savePlayer (file:///home/andrei/src/sousmarin/lib/db.dart:37:45)
E/flutter (22209): <asynchronous suspension>
E/flutter (22209): #3      PlayersRegister.savePlayer (file:///home/andrei/src/sousmarin/lib/services/players.dart:31:9)
E/flutter (22209): #4      _PlayersListState._onPlayerChanged.<anonymous closure> (file:///home/andrei/src/sousmarin/lib/players_list.dart:28:36)
E/flutter (22209): #5      State.setState (package:flutter/src/widgets/framework.dart:1117:30)
E/flutter (22209): #6      _PlayersListState._onPlayerChanged (file:///home/andrei/src/sousmarin/lib/players_list.dart:28:7)
E/flutter (22209): #7      _PlayerItemWidgetState.build.<anonymous closure>.<anonymous closure> (file:///home/andrei/src/sousmarin/lib/players_list.dart:123:22

**Comment by andreiboyanov** [comment]
Looks like something in the sembast package...
